baseURL = 'https://fimblo.github.io/'
languageCode = 'en-us'
title = "fimblo's blog"
theme = 'cactus'


summaryLength = 5

[[menu.main]]
name = "Home"
url = "/"
weight = 1


[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false


  [[params.social]]
    name = "github"
    link = "https://github.com/fimblo"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/mattiasjansson"
  [[params.social]]
    name = "email"
    link = "m@yanson.org"
